# Generated by Django 3.0.7 on 2020-06-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20200613_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition_information',
            old_name='one_serviong_kcal',
            new_name='one_serving_kcal',
        ),
    ]
