# Generated by Django 3.0.7 on 2020-06-14 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_auto_20200614_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy_drink',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Allergy'),
        ),
        migrations.AlterField(
            model_name='allergy_drink',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.Drink'),
        ),
    ]
